### ISSUE TITLE
Spec-compliance?

### ISSUE THREAD

**Issue by rubensworks** [rdf-ext/rdf-parser-csvw#26]
I was wondering if this parser is fully spec-compliant?
And if not, what parts of the spec are (not) implement (yet).

An implementation report for the [CSVW RDF Tests](https://w3c.github.io/csvw/tests/#manifest-rdf) may be a good indication.

**Comment by ktk** [comment]
No it is not, we implemented what we needed so far and from our side we have no plans to implement the full spec at the moment.

There are a few issues with that spec, @bergos can comment on them as well but the things I remember are:

- Some parts of the spec break streaming. We needed this for large datasets so we completely skip everything that would potentially break streaming.
- The tests are not properly separated. In our opinion a test should test one thing, that's why we started adding tests on our own. In the official test suite multiple things get tested at the same time, which makes it really hard to test for breaking changes.

We also had some critical remarks regarding the spec but they were mostly declared as "not a problem" so we ignored those as well. We can elaborate more if you are curious (maybe a call or something).

But we are definitely interested in contributions in case you have specific requirements.

**Comment by rubensworks** [comment]
Thanks for the quick reply!

> Some parts of the spec break streaming.

I encountered this as well in some other specs.
What I typically do in my implementations, is introducing a streaming-mode.
When this is enabled, it would make some assumptions that could perhaps not be fully spec-compliant.

> The tests are not properly separated. In our opinion a test should test one thing, that's why we started adding tests on our own. In the official test suite multiple things get tested at the same time, which makes it really hard to test for breaking changes.

I haven't looked at the spec test myself, but adding smaller unit tests yourself definitely sounds like a good idea :-)

> But we are definitely interested in contributions in case you have specific requirements.

My use case would be adding CSVW support to Comunica to enable querying. The most important thing here would be full spec-compliance. So our requirements may be quite different.

**Comment by ktk** [comment]
> My use case would be adding CSVW support to Comunica to enable querying. The most important thing here would be full spec-compliance. So our requirements may be quite different.

Ok then I would propose that we have a talk with Thomas as well. I'm sure we can find a way that benefits all of us and makes the codebase more powerful.

**Comment by ktk** [comment]
To summarize our talk a while ago:

* We are open for contributions to this repo
* Rubens plan is full spec-compliance, which this repo probably will not achieve
* Ruben might use this as a base if appropriate for some future work he considers (probably in a separate repo)
* Pull requests are welcome
